---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  GitHubUserName:
    Type: String
  GitHubOAuthToken:
    Type: String
    NoEcho: true
  ApplicationName:
    Type: String
    Default: r6trackercom
  EnvironmentName:
    Type: String
    Default: r6trackercom-env
Resources:
  ArtifactsBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
  Pipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactsBucket
      Name: 'r6tracker.com'
      RestartExecutionOnUpdate: true
      RoleArn: !Sub '${PipelineRole.Arn}'
      Stages:
      - Name: Source
        Actions:
        - Name: SourceAction
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Provider: GitHub
            Version: 1
          Configuration:
            Owner: !Ref GitHubUserName
            Repo: 'r6tracker.com'
            Branch: master
            OAuthToken: !Ref GitHubOAuthToken
          OutputArtifacts:
          - Name: Zip
          RunOrder: 1
      - Name: DeployPipeline
        Actions:
        - Name: DeployPipelineAction
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: 1
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_IAM
            RoleArn: !Sub '${CloudFormationRole.Arn}'
            StackName: 'r6trackercom-DeployStack'
            TemplatePath: 'Zip::pipeline.yml'
            ParameterOverrides: !Sub '{"GitHubUserName": "${GitHubUserName}", "GitHubOAuthToken": "${GitHubOAuthToken}"}'
          InputArtifacts:
          - Name: Zip
          RunOrder: 1
      - Name: DeployApplication
        Actions:
        - Name: DeployApplicationStackAction
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: 1
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_IAM
            RoleArn: !Sub '${CloudFormationRole.Arn}'
            StackName: 'r6trackercom-Stack'
            TemplatePath: 'Zip::application.yml'
            ParameterOverrides: {
              "ApplicationName": { "Ref": "ApplicationName" },
              "EnvironmentName": { "Ref": "EnvironmentName" }
            }
          InputArtifacts:
          - Name: Zip
          RunOrder: 1
        - Name: DeployApplicationAction
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: ElasticBeanstalk
            Version: 1
          Configuration:
            ApplicationName: !Ref ApplicationName
            EnvironmentName: !Ref EnvironmentName
          InputArtifacts:
          - Name: Zip
  PipelineRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'codepipeline.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AdministratorAccess'
  CloudFormationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'cloudformation.amazonaws.com'
          Action:
          - 'sts:AssumeRole'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AdministratorAccess'